### ISSUE TITLE
problem installing structurizr-cli

### ISSUE THREAD

**Issue by rdmueller** [bitsmuggler/arc42-c4-software-architecture-documentation-example#1]
it seems that not every version of `tar` can handle `.zip` files

```
> curl --show-error --location https://static.structurizr.com/download/structurizr-cli.zip | tar -xf - -C bin/structurizr-cli
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0tar: This does not look like a tar archive
tar: Skipping to next header
100 81.4M  100 81.4M    0     0   171M      0 --:--:-- --:--:-- --:--:--  170M
tar: Exiting with failure status due to previous errors
```

The following line works for me:

```
curl --show-error --location https://static.structurizr.com/download/structurizr-cli.zip  -o tmp.zip && unzip -d bin/structurizr-cli/. tmp.zip && rm tmp.zip
```

**Comment by rdmueller** [comment]
so, the differences with tar-commands was one problem, the broken url is another.

How did you find the version-less link? Should we ask Simon about it?

**Comment by bitsmuggler** [comment]
Hi @rdmueller 

Thanks for your answer.

I created an issue on the [structurizr-cli](https://github.com/structurizr/cli) project, see: https://github.com/structurizr/cli/issues/104

Kind regards, Patrick

**Comment by rdmueller** [comment]
So, it aeems we have to use the versioned URLs. ...

**Comment by bitsmuggler** [comment]
Yes, for the local installation. For the Docker way, there is a Latest tag. I'll probably describe the local installation like this:

 * `curl --show-error --location https://github.com/structurizr/cli/releases/download/v{selected-version}/structurizr-cli-{selected-version}.zip  -o tmp.zip && unzip -d bin/structurizr-cli/. tmp.zip && rm tmp.zip`

**Comment by rdmueller** [comment]
yes, I think this is the way to go. let's close this issue...

**Comment by bitsmuggler** [comment]
@rdmueller I've also added the description of using structurizr cli with Docker
