### ISSUE TITLE
Add GitHub actions

### ISSUE THREAD

**Issue by bitsmuggler** [bitsmuggler/arc42-c4-software-architecture-documentation-example#8]
* Build the documentation
* Upload & version the artifacts
* Deploy the HTML Artifact to Netlify or Vercel

**Comment by rdmueller** [comment]
you can use github pages.

This repository contains the code for github pages and gitlab pages: https://github.com/docToolchain/ci-cd-demo

**Comment by bitsmuggler** [comment]
Yeah, thanks for your help, @rdmueller 👍 .

👉  https://bitsmuggler.github.io/arc42-c4-software-architecture-documentation-example/  😄

**Comment by rdmueller** [comment]
very cool!
